### ISSUE TITLE
Missing pthreads with gbench enabled build

### ISSUE THREAD

**Issue by travisdowns** [tetzank/interleaved-algorithms#1]
On Linux, linking to newest gbench, linking fails because of a dependency on pthreads.

**Comment by tetzank** [comment]
On ArchLinux, libbenchmark.so links against pthread. Therefore, it should not be required for binary_search_bench to link against pthreads as well. It does not use it.

Added it anyway as the official google benchmark documentation also has it in there. Well...

**Comment by travisdowns** [comment]
@tetzank - in my case, the makefile links not against `libbenchmark.so` but `libbenchmark.a` so the pthreads dep would need to be available at compile time.

Here's the full error on my system.

```
/usr/local/lib/libbenchmark.a(benchmark_runner.cc.o): In function `std::thread::thread<void (*)(benchmark::internal::BenchmarkInstance const*, unsigned long, int, benchmark::internal::ThreadManager*), benchmark::internal::BenchmarkInstance const*, unsigned long&, int, benchmark::internal::ThreadManager*>(void (*&&)(benchmark::internal::BenchmarkInstance const*, unsigned long, int, benchmark::internal::ThreadManager*), benchmark::internal::BenchmarkInstance const*&&, unsigned long&, int&&, benchmark::internal::ThreadManager*&&)':
/usr/include/c++/5/thread:138: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/binary_search_bench.dir/build.make:95: recipe for target 'binary_search_bench' failed
make[2]: *** [binary_search_bench] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/binary_search_bench.dir/all' failed
make[1]: *** [CMakeFiles/binary_search_bench.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

You didn't mention exactly how to configure the system to find google benchmark, so I just build & `make install` the google benchmark per the instructions in that repo, and I guess it installs only the `*.a` in that case?

```
$ ls /usr/local/lib/libbenchmark*
/usr/local/lib/libbenchmark.a  /usr/local/lib/libbenchmark_main.a
```

It seems the default is for the static library, you have to ask for the shared library explicitly with [cmake -DBUILD_SHARED_LIBS=ON](https://stackoverflow.com/questions/13513905/how-to-setup-googletest-as-a-shared-library-on-linux)?

**Comment by tetzank** [comment]
Looks like it. When you link libbenchmark statically, you have to link every dependency of it explicitly, such as pthreads. I guess that's the reason why they have it in their documentation as well. It doesn't harm to link against pthreads anyway.

Btw, thanks for the fixes.
